### ISSUE TITLE
Comments making it through the blacklist

### ISSUE THREAD

**Issue by deebz** [splorp/wordpress-comment-blacklist#25]
Just a heads up - had some comments making it past the black list and into the comment moderation cue. Most of them about bitcoin, even though similar comments got binned straight away. 

Emails an IP's I redacted as they're probably compromised accounts.

![spam](https://user-images.githubusercontent.com/462011/69431919-9190d200-0d30-11ea-8d5d-7f7d0382ffa2.png)

**Comment by splorp** [comment]
Thanks for passing this along, @deebz.

The primary reason these comments weren’t caught is that the blacklist does not include simple, standalone terms such as _“forex”_, _“bitcoin”_, or _“BTC”_. This is because legitimate comments may contain these terms as part of completely benign statements.

However, I will look into adding more of the suspect phrases which include these specific terms.

For example:

_“Forex + Bitcoin”_
_“Forex + Crypto”_
_“Bitcoin per week”_

Do you still happen to have copies of these comments? It would be useful to have text versions of anything that didn’t caught caught by the blacklist.

**Comment by splorp** [comment]
@deebz Based on your screenshot, I will be adding the following terms to the blacklist over the next day or so:

```
bitcoin + crypto
bitcoin $
bitcoin from $
bitcoin per day
bitcoin per week
bitcoin-per-day
bitcoin-per-week
btc + crypto
btc $
btc from $
btc per day
btc per week
btc-per-day
btc-per-week
forex + bitcoin
forex + btc
forex + crypto
forex $
invest in bitcoin
invest in btc
invest in crypto
invest-in-bitcoin
invest-in-btc
invest-in-crypto
investing in bitcoin
investing in btc
investing in crypto
investing-in-bitcoin
investing-in-btc
investing-in-crypto
investment in bitcoin
investment in btc
investment in crypto
investment-in-bitcoin
investment-in-btc
investment-in-crypto
investments in bitcoin
investments in btc
investments in crypto
investments-in-bitcoin
investments-in-btc
investments-in-crypto
make more loan
make-more-loan
```

Hopefully, this update will help nab the majority of the renegade comments.

Please pass along any additional comment text that doesn’t get caught.

**Comment by deebz** [comment]
That's fantastic. Thank you for producing this invaluable tool

**Comment by splorp** [comment]
You’re welcome.

The new terms were added in commit a3329ff
