### ISSUE TITLE
Domains to add

### ISSUE THREAD

**Issue by borpin** [splorp/wordpress-comment-blacklist#26]
felphi.com
jaffx.com

**Comment by splorp** [comment]
Hi Brian.

Thanks for the suggestions. Do you have any examples of the spam that included these domains? Sometimes the content of the comments (including the email addresses and links) can provide very useful information regarding the source and style of spam.

**Comment by borpin** [comment]
It is spam registrations. Here are 3 today.

![image](https://user-images.githubusercontent.com/1322749/78635899-18d58100-789f-11ea-9a0a-852352b13b47.png)

![image](https://user-images.githubusercontent.com/1322749/78636081-779afa80-789f-11ea-9b1b-85c3a6775425.png)

I do have a catptcha on the registrations page.

It is often followed by a password reset request.

**Comment by splorp** [comment]
Ok, thanks.

**Comment by mauwiks** [comment]
Same just got my registration turned on and I received these:

wesley_schiassi240@alilen.pw
eric.riccio4459@digital2mail.com
dannycady@from.crossandgarlic.com
billy.davis3004@digital2mail.com
bennett.cambell9754@lavarip.xyz
lanny.nepean8970@lavarip.xyz
gabriella.lowrie9706@lavarip.xyz
jerome.hillary@highspeed.catchallserver.com
adam_guzzi@happy.blurmailbox.com
pasquale-wakehurst@alilen.pw
eleanore-mccloud@alilen.pw

Screenshot: https://bit.ly/2RK3dFR

P.S. Couldn't screenshot all and not sure if they are spam but in my theory, they are.

**Comment by splorp** [comment]
I hesitate to add email domains that have been used for user registrations to the blacklist. Unless the domains are URL shorteners (as noted in [the read me](https://github.com/splorp/wordpress-comment-blacklist#known-issues-limitations--other-gotchas)), they should be considered as valid, legitimate domains.

User registrations are harder to filter because they are not accompanied by any additional links or text, like comments are.

If you find that you are getting multiple bogus registrations from the same email domain, consider using a plugin such as [Comment Blacklist Manager](https://wordpress.org/plugins/comment-blacklist-manager/) and adding your site-specific terms to the Local Blacklist field. The plugin will automatically update the primary blacklist from my repository, but also include your custom terms from the local list.

**Comment by borpin** [comment]
> consider using a plugin such as [Comment Blacklist Manager](https://wordpress.org/plugins/comment-blacklist-manager/)

Boom. I've been looking for such a things for ages - just what I need. I'd missed it in your readme.
